# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.salt.validators


class Migration(migrations.Migration):

    dependencies = [("salt", "0002_user_active")]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.CharField(
                max_length=512,
                validators=[outpost.django.salt.validators.RelativePathValidator()],
            ),
        )
    ]
