# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0053_external"),
        ("salt", "0004_auto_20200805_1403"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="salt.User",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campusonline.External",
                    ),
                ),
            ],
            options={"manager_inheritance_from_future": True},
            bases=("salt.user",),
        )
    ]
