# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0005_externaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=512, validators=[outpost.django.base.validators.NormalizedPathValidator(), outpost.django.base.validators.RelativePathValidator()]),
        ),
    ]
