# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.utils
import storages.backends.sftpstorage
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0006_auto_20201217_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(storage=settings.SALT_FILE_STORAGE, upload_to=outpost.django.base.utils.Uuid4Upload),
        ),
    ]
