# Generated by Django 2.2.28 on 2023-09-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salt", "0007_auto_20210402_2341"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externaluser",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="host",
            options={"ordering": ("name",), "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="staffuser",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="studentuser",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="system",
            options={"ordering": ("name",)},
        ),
    ]
