# Generated by Django 2.2.28 on 2024-03-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salt", "0008_auto_20230919_1113"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDirectory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.TextField()),
                ("permissions", models.CharField(default="0700", max_length=4)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salt.System"
                    ),
                ),
            ],
        ),
    ]
