# Generated by Django 5.2.16 on 2026-09-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("salt", "0009_userdirectory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externaluser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="staffuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="studentuser",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
