# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 08:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0011_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('content', models.FileField(upload_to=outpost.django.base.utils.Uuid4Upload)),
                ('sha256', models.CharField(max_length=64)),
                ('permissions', models.CharField(default='0640', max_length=4, validators=[django.core.validators.RegexValidator('^0?[0-7]{3}$', 'Not a valid POSIX permission.')])),
                ('mimetype', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.File')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.System')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='systems',
            field=models.ManyToManyField(blank=True, through='salt.SystemFile', to='salt.System'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.User'),
        ),
    ]
