# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE VIEW "public"."salt_job" AS SELECT
                jid AS id,
                load AS data
            FROM
                "salt"."jids";
            """,
            """
            DROP VIEW IF EXISTS "public"."salt_job";
            """,
        ),
        (
            """
            CREATE VIEW "public"."salt_result" AS SELECT
                pk AS id,
                fun AS function,
                jid AS job_id,
                return AS result,
                id AS target,
                success::boolean AS success,
                full_ret AS data,
                alter_time AS modified
            FROM
                "salt"."salt_returns";
            """,
            """
            DROP VIEW IF EXISTS "public"."salt_result";
            """,
        ),
        (
            """
            CREATE VIEW "public"."salt_event" AS SELECT
                id,
                tag,
                data,
                alter_time AS modified,
                master_id AS master

            FROM
                "salt"."salt_events";
            """,
            """
            DROP VIEW IF EXISTS "public"."salt_event";
            """,
        ),
    ]

    dependencies = [
        ('salt', '0012_auto_20191016_1050'),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
